# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kiarash Sedghi 
title: Ph.D. student of Computer Science & Engineering at USF
email: kiarashs@usf.edu
gmail: kiarash.sedghi99@gmail.com


# Dark Mode (true/false/never)
darkmode: true

# Social links

#twitter_username: facespics
github_username:  gkiarashv
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: kiarash-sedghi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: CV
  icon: cv.png
  url: https://www.dropbox.com/s/nvo8byg7i6gceow/CV.pdf?dl=0
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/kiarashprof.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm Ph.D. student of Computer Science and Engineering at USF (University of South Florida, U.S.). My field of study is "Applied cryptography". My research interests
  include: <mark>Cryptography</mark>, <mark>Malware analysis</mark>, <mark>Binary exploitation</mark>, and <mark>Reverse engineering</mark>.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Smart grid gateway
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          B.S. thesis project
        description: | # this will include new lines to allow paragraphs
          As B.S. thesis, Idesigned and implemented a gateway responsible for translating the two most-used protocols (standards) in the Smart Grid. Firstly, this gateway enablesold and new devices using different standards to exist, and cooperate in anoperational environment. Secondly, it is optimized and cost-efficient, which canbe developed and deployed with low financial investment.

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of South Florida, U.S.
        caption: 2023 - present
        sub_title: Ph.D. Computer Science & Engineering
        description: | # this will include new lines to allow paragraphs
          Ph.D. research in designing and utilizing cryptographic tools to enhance thesecurity of computer networks and systems under direction of Prof. <a href="https://cse.usf.edu/~attilaayavuz/">Attila A.Yavuz</a>
      - layout: left
        title: University of Isfahan, Iran
        caption: 2017 - 2021
        sub_title: B.S. Computer Science & Engineering
        description: | # this will include new lines to allow paragraphs
          B.S. thesis in designing "Smart grid gateway" under direction of Prof. <a href="https://engold.ui.ac.ir/~shahgholi/">Behrouz Shahgholi Ghahfarokh</a>
  
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
